version: "3.2"

services:
  api:
    image: "registry.thinklabs.com.vn:5000/tclinicAiApi:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.environment==development]
      restart_policy:
        condition: any
    ports:
      - target: 8080
        published: 8084
        mode: host
    environment:
      PORT: 8080
      NODE_ENV: "production"
      SERVICE_3003_NAME: "tclinicaiapi"
      SERVICE_NAME: "tclinicaiapi"
      SERVICE_TAGS: "tclinicaiapi"
    volumes:
      - "resources:/usr/src/app/resources"

volumes:
  resources:
    driver: lizardfs
